-- grand_prix.lua  —  generated by MissionForge. DEPLOY: scripts/OnLoad/ with a HIGHER
-- lua_loader.ini [OnLoad] number than ContractFramework.lua (so it loads after the framework).

if not _G.Contract then
    Loader.Printf("grand_prix: Contract framework not loaded - give ContractFramework.lua a LOWER [OnLoad] number")
    return
end

Contract.Register({
    id       = "grand_prix",
    title    = "Maracaibo Grand Prix",
    category = "RACE",
    briefing = "Race from the PMC HQ all the way to Maracaibo!",
    reward   = { cash = 10000, fuel = 20 },
    start    = { x = 2651.78, y = -13.72, z = -1014.94, yaw = 146.033 },

    objectives = {
        Contract.Race({ desc = "Hit all 24 checkpoints", radius = 15, time = 240, checkpoints = {
            { 2682.45, -13.75, -1048.43 },
            { 2845.48, -24.65, -1196.91 },
            { 2905.01, -27.06, -1167.65 },
            { 2924.88, -33.15, -1093.84 },
            { 2933.77, -34.78, -1025.12 },
            { 2927.34, -35.35, -943.48 },
            { 2937.54, -33.06, -863.7 },
            { 2937.62, -29.97, -790.23 },
            { 2945.57, -28.55, -695.87 },
            { 2956.74, -28.47, -593.04 },
            { 2963.57, -29.01, -505.72 },
            { 2930.01, -30.95, -408.18 },
            { 2854.84, -34.67, -310.38 },
            { 2740.97, -32.13, -203.18 },
            { 2691.99, -32.19, -115.17 },
            { 2727.06, -31.95, -36.19 },
            { 2726.39, -32.14, 48.06 },
            { 2641.34, -31.23, 99.83 },
            { 2556.34, -24.13, 165.07 },
            { 2562.58, -12.33, 256.37 },
            { 2637.38, -13, 314.23 },
            { 2672.75, -19.85, 403.6 },
            { 2678.73, -29.19, 485.13 },
            { 2673.28, -33.97, 545.14 },
        } }),
        Contract.Extract({ desc = "Reach extraction", at = { 2673.43, -33.81, 617.33 }, radius = 15, boardTime = 1, heli = "UH1 Transport (GR) (Ewan)" }),
    },

    fResolve = function(def)
        -- provided units (not tied to an objective) - spawned when the contract is accepted:
        Pg.Spawn("Veyron", 2662.76, -11.5, -1032.93, 137.154)
        Pg.Spawn("Veyron", 2667.54, -11.5, -1028.73, 136.407)
    end,
})